<?xml version="1.0" encoding="utf-8"?><Database Name="CSDL_QLVS" Class="CSDL_QLVSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-8JC9R37\SQLEXPRESS;Initial Catalog=CSDL_QLVS;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CSDL_QLVSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LopHoc" Member="LopHocs">
    <Type Name="LopHoc">
      <Column Name="MaLop" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="LopHoc_SInhVien" Member="SInhViens" ThisKey="MaLop" OtherKey="MaLop" Type="SInhVien" />
    </Type>
  </Table>
  <Table Name="dbo.SInhVien" Member="SInhViens">
    <Type Name="SInhVien">
      <Column Name="Ma" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NamSinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaLop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LopHoc_SInhVien" Member="LopHoc" ThisKey="MaLop" OtherKey="MaLop" Type="LopHoc" IsForeignKey="true" />
    </Type>
  </Table>
</Database>